version: '2'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2023
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "10017:8069"
      - "20017:8072"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo17@2023
      - WEB_BASE_URL=http://192.168.1.4
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
  
  generate-cert:
    image: alpine
    volumes:
      - ./ssl:/ssl
    entrypoint: >
      sh -c "apk add openssl && 
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 
      -keyout /ssl/odoo.key -out /ssl/odoo.crt 
      -subj '/CN=odoo.local'"
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - odoo
    entrypoint: >
      sh -c "while [ ! -f /etc/nginx/ssl/odoo.crt ]; do echo 'Waiting for cert...'; sleep 2; done && nginx -g 'daemon off;'"


networks:
  default:
    driver: bridge
